kind: ClusterIssuer
apiVersion: cert-manager.io/v

metadata:
  name: letsencrypt-prod

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory

    email: tanujnimkar2016@gmail.com

    privateKeySecretRef:
      name: letsencrypt-prod-key

    solvers:
      - http01:
          ingress:
            class: nginx
