apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudnative-commerce-config
  namespace: cloudnative-commerce

data:
  MONGODB_URI: "mongodb://mongodb-service:27017/cloudnative-commerce"

  NODE_ENV: "production"

  NEXT_PUBLIC_API_URL: "https://cloudnative.tanujdevops.site/api"

  NEXTAUTH_URL: "https://cloudnative.tanujdevops.site/"

  NEXTAUTH_SECRET: "replace-with-your-own-secret"

  JWT_SECRET: "replace-with-your-own-jwt-secret"