apiVersion: v1
kind: Secret

metadata:
  name: cloudnative-commerce-secrets
  namespace: cloudnative-commerce

type: Opaque

stringData:
  JWT_SECRET: "generated-jwt-secret"

  NEXTAUTH_SECRET: "generated-nextauth-secret"