apiVersion: batch/v1
kind: Job

metadata:
  name: db-migration
  namespace: cloudnative-commerce

spec:
  template:

    spec:
      containers:

        - name: migration

          image: tanuj7777777/cloudnative-commerce-migration:1

          imagePullPolicy: Always

          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/cloudnative-commerce"

      restartPolicy: OnFailure
